// <auto-generated />
using System;
using BrownieShop.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrownieShop.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260419053203_FixBrownieSeed")]
    partial class FixBrownieSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BrownieShop.API.Models.Brownie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Brownies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Rich dark chocolate, dense and fudgy. The one that started it all.",
                            ImageUrl = "🍫",
                            Name = "Classic Brownie",
                            Price = 60m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Classic brownie loaded with crunchy California walnuts on every bite.",
                            ImageUrl = "🌰",
                            Name = "Walnut Brownie",
                            Price = 75m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Double chocolate — fudgy base + melted choco chips throughout.",
                            ImageUrl = "🍪",
                            Name = "Choco Chip Brownie",
                            Price = 70m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Crushed Oreo cookies baked right into our signature brownie batter.",
                            ImageUrl = "⚫",
                            Name = "Oreo Brownie",
                            Price = 80m
                        },
                        new
                        {
                            Id = 5,
                            Description = "A swirl of Nutella baked into every bite. Pure indulgence.",
                            ImageUrl = "🫙",
                            Name = "Nutella Brownie",
                            Price = 90m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Warm brownie topped with vanilla ice cream and chocolate drizzle.",
                            ImageUrl = "🍨",
                            Name = "Brownie Sundae",
                            Price = 120m
                        });
                });

            modelBuilder.Entity("BrownieShop.API.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrownieId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrownieId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BrownieShop.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BrownieShop.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrownieId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrownieId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BrownieShop.API.Models.CartItem", b =>
                {
                    b.HasOne("BrownieShop.API.Models.Brownie", "Brownie")
                        .WithMany()
                        .HasForeignKey("BrownieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brownie");
                });

            modelBuilder.Entity("BrownieShop.API.Models.OrderItem", b =>
                {
                    b.HasOne("BrownieShop.API.Models.Brownie", "Brownie")
                        .WithMany()
                        .HasForeignKey("BrownieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrownieShop.API.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brownie");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BrownieShop.API.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
